#!/bin/bash

# This MUST be customized to your local path.
cxpath=/home/ed/projects/daborun/cx_Freeze

# For testing the runtime engine only. This will
# copy files generated by the appWizard so that a 
# real Dabo app can be tested.
copyTestApp=0

### Dabo Runtime Engine ###
mainScript=~/projects/daborun/daborun.py
outDir=$cxpath/daborun
outName=daborun
copyTestApp=1

### Bubblet ###
# mainScript=~/projects/demo/bubblet/main.py
# outDir=$cxpath/bubb
# outName=Bubblet

### Simple Bizobj Form ###
# mainScript=~/projects/demo/SimpleFormWithBizobj.py
# outDir=$cxpath/simp
# outName=SimpleBiz

### Simple Form ###
# mainScript=~/projects/demo/SimpleFormWithControls.py
# outDir=$cxpath/simp
# outName=SimpleForm

cd $cxpath
rm -rf $outDir

# Do we try to put all the supporting files in a 'lib' directory?
uselib=1

# ./FreezePython --install-dir=eng --base-binary=$cxpath/ConsoleSetLibPathBase ~/projects/daboEngine/daboEngine.py
./FreezePython \
        --install-dir=$outDir \
        --target-name=$outName \
        --init-script=ConsoleSetLibPath \
        $mainScript
#       --include-modules=wx,dabo,time \

cd $outDir

#echo "******"
#ls -l
#echo "******"

for i in *.so
do
    if chrpath $i 2>/dev/null | grep = >/dev/null
    then
        echo "Fixing $i"
        chrpath -d $i
    else
        echo "no rpath or runpath tag found for $i"
    fi
done

cd $outDir
if [ $uselib -ne 0 ]; then
        echo "USE LIB"
        mkdir /tmp/dabolib
        mv * /tmp/dabolib/
        mv /tmp/dabolib/$outName .
        mv /tmp/dabolib .
        cp ~/projects/dabo/icons/*png dabolib/
else
        echo "DON'T USE LIB"
        cp ~/projects/dabo/icons/*png .
fi

if [ $copyTestApp -eq 1 ]; then
	# Customize this path to one containing a Dabo app
        cp ~/projects/demo/dls/* .
        rm -f *pyc
fi

echo "Completed freeze in directory: $outDir"
